---
engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
    checks:
      adjoining-classes:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- vendor/**/*
- db/**/*
- config/**/*
- app/lib/**/*