source 'https://rubygems.org'

gem 'thor'
gem 'byebug'
gem 'rspec'
gem 'ruby-progressbar'
gem 'descriptive_statistics'
gem 'require_all'
gem 'draper'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'activesupport'