---
default_query: (Resolution = 'Done' or Resolution = 'Fixed') and not (issue_type = 'Epic' or filter = 'Kaizen' or filter = 'Releases' or filter = 'Outliers')
sync:
  months: 6
filters:
- name: Kaizen
  query: labels = 'kaizen'
- name: Releases
  query: labels = 'release'
- name: Outliers
  issues:
  - key: MOB-1110
  - key: MOB-1584
  - key: MOB-78
  - key: MOB-2084
  - key: MOB-2164
  - key: MOB-2172
  - key: MOB-2088
  - key: MOB-2041
  - key: MOB-2061
  - key: MOB-2075
  - key: MOB-2269
  - key: MOB-2564
  - key: MOB-2005
  - key: MOB-2006
  - key: MOB-2002
  - key: MOB-1909
  - key: MOB-1971
  - key: MOB-1991
  - key: MOB-2750
  - key: MOB-2137
  - key: MOB-2804
  - key: MOB-1294
  - key: MOB-1811
