---
url: https://jira.zipcar.com
name: Zipcar
fields:
- Developer
- Platform Verticals
- Target Date
- Metric Adjustments
- Teams
- Resolution
increments:
- issue_type: Delivery
  inward_link_type: is included in
  outward_link_type: includes
status_category_overrides:
- map: Ready
  to_category: To Do
boards:
  # Training
  - board_id: 726
  # In Progress
  - board_id: 723
    config_url: https://stash.zipcar.com/projects/QE/repos/jira-team-metrics-configs/raw/AgileTools_InProgress_Issues.yml
  - board_id: 754
    config_url: https://stash.zipcar.com/projects/QE/repos/jira-team-metrics-configs/raw/AgileTools_Mobile_Issues.yml
teams:
  - name: Member Web
    short_name: mweb
  - name: Member Comms
    short_name: mcom
