---
type: "//rec"
optional:
  default_query:
    type: "//str"
  epics:
    type: "//rec"
    optional:
      counting_strategy: "//str"
      link_missing: "//bool"
  filters:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        name: "//str"
        type: "//str"
        query: "//str"
  predictive_scope:
    type: "//rec"
    required:
      board_id: "//int"
      adjustments_field: "//str"
  timesheets:
    type: "//rec"
    optional:
      additional_columns:
        type: "//arr"
        contents: "//str"
      reporting_period:
        type: "//rec"
        required:
          day_of_week: "//int"
          duration:
            type: "//rec"
            required:
              days: "//int"
  rolling_window:
    type: "//rec"
    required:
      days: "//int"
  sync:
    type: "//rec"
    required:
      months: "//int"

  reports: "/metrics/reports-config"