---
type: "//rec"
optional:
  default_query:
    type: "//str"
  filters:
    type: "//arr"
    contents:
      type: "//any"
      of:
        - type: "//rec"
          required:
            name: "//str"
            jql: "//str"
        - type: "//rec"
          required:
            name: "//str"
            mql: "//str"
        - type: "//rec"
          required:
            name: "//str"
            issues:
              type: "//arr"
              contents:
                type: "//rec"
                required:
                  key: "//str"
                optional:
                  reason: "//str"
  predictive_scope:
    type: "//rec"
    required:
      board_id: "//int"
      adjustments_field: "//str"
  timesheets:
    type: "//rec"
    optional:
      additional_columns:
        type: "//arr"
        contents: "//str"
      reporting_period:
        type: "//rec"
        required:
          day_of_week: "//int"
          duration:
            type: "//rec"
            required:
              days: "//int"
  rolling_window:
    type: "//rec"
    required:
      days: "//int"
  sync:
    type: "//rec"
    required:
      months: "//int"

