---
type: "//rec"
optional:
  default_query:
    type: "//str"
  cycle_times:
    type: "//rec"
    required:
      in_test:
        type: "//rec"
        required:
          from: "//str"
          to: "//str"
      in_review:
        type: "//rec"
        required:
          from: "//str"
          to: "//str"
      in_progress:
        type: "//rec"
        required:
          from: "//str"
          to: "//str"
  filters:
    type: "//arr"
    contents:
      type: "//any"
      of:
        - type: "//rec"
          required:
            name: "//str"
            query: "//str"
        - type: "//rec"
          required:
            name: "//str"
            issues:
              type: "//arr"
              contents:
                type: "//rec"
                required:
                  key: "//str"
                optional:
                  reason: "//str"
  predictive_scope:
    type: "//rec"
    required:
      board_id: "//int"
      adjustments_field: "//str"
  sync:
    type: "//rec"
    optional:
      since: "//str"
      subquery: "//str"

