---
type: "//rec"
required:
  url: "//str"
optional:
  name: "//str"
  fields:
    type: "//arr"
    contents: "//str"
  projects:
    type: "//rec"
    required:
      issue_type: "//str"
      inward_link_type: "//str"
      outward_link_type: "//str"
  epics:
    type: "//rec"
    optional:
      counting_strategy: "//str"
      link_missing: "//bool"
  boards:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        board_id: "//int"
      optional:
        config_file: "//str"
  teams:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        name: "//str"
        short_name: "//str"
  tags:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        name: "//str"
        path: "//str"
  reports: "/metrics/reports-config"
