---
type: "//rec"
required:
  url: "//str"
optional:
  name: "//str"
  fields:
    type: "//arr"
    contents: "//str"
  projects:
    type: "//rec"
    required:
      issue_type: "//str"
      inward_link_type: "//str"
      outward_link_type: "//str"
  status_category_overrides:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        map: "//str"
        to_category: "//str"
  boards:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        board_id: "//int"
      optional:
        config_file: "//str"
  teams:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        name: "//str"
        short_name: "//str"
  reports:
    type: "//rec"
    optional:
      epics:
        type: "//rec"
        required:
          sections:
            type: "//arr"
            contents:
              type: "//rec"
              required:
                title: "//str"
                mql: "//str"
      projects:
        type: "//rec"
        required:
          sections:
            type: "//arr"
            contents:
              type: "//rec"
              required:
                title: "//str"
                mql: "//str"
