---
type: "//rec"
optional:
  epics:
    type: "//rec"
    optional:
      backing_query: "//str"
      card_layout:
        type: "//rec"
        optional:
          fields:
            type: "//arr"
            contents: "//str"
    required:
      sections:
        type: "//arr"
        contents:
          type: "//rec"
          required:
            title: "//str"
            mql: "//str"
          optional:
            collapsed: "//bool"
            min: "//int"
            max: "//int"
  projects:
    type: "//rec"
    optional:
      backing_query: "//str"
      card_layout:
        type: "//rec"
        optional:
          fields:
            type: "//arr"
            contents: "//str"
    required:
      sections:
        type: "//arr"
        contents:
          type: "//rec"
          required:
            title: "//str"
            mql: "//str"
          optional:
            collapsed: "//bool"
  scatterplot:
    type: "//rec"
    optional:
      default_query: "//str"
  throughput:
      type: "//rec"
      optional:
        default_query: "//str"
  aging_wip:
    type: "//rec"
    optional:
      default_query: "//str"
      fields:
        type: "//arr"
        contents: "//str"
