---
type: "//rec"
required:
  url: "//str"
optional:
  name: "//str"
  fields:
    type: "//arr"
    contents: "//str"
  increments:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        issue_type: "//str"
        inward_link_type: "//str"
        outward_link_type: "//str"
  status_category_overrides:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        map: "//str"
        to_category: "//str"
  boards:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        jira_id: "//int"
        config_url: "//str"
